In [1]:
#姓名：刘子璇
#班级：2016级4班
#学号：2016011481

In [2]:
#1. 设计一个函数，要求输入两个`shape、dtype`一样的张量，输出一个同样`shape、dtype`的张量，并且输出的张量中的元素的每一个值都是输入的两个张量
#中对应元素最大的。即模拟`tf.maximum`的功能，但不能直接使用此函数。
import tensorflow as tf
n1 = tf.constant(1)
n2 = tf.constant(2)
def mymax(num1,num2):
    result = tf.cond(num1>num2,lambda:num1,lambda:num2)
    with tf.Session() as sess:
        print(result.eval())
mymax(n1,n2)

2


In [3]:
#2.了解`tf.minimum`、`tf.maximum`的用法

#tf.maximum：用法tf.maximum(a,b),返回的是a,b之间的最大值
#tf.miniimum：用法tf.miiinimum(a,b),返回的是a,b之间的最小值
import tensorflow as tf
a = [1,5,3] 
f1 = tf.maximum(a, 3) 
f2 = tf.minimum(a, 3) 
with tf.Session() as sess: 
    print(sess.run(f1))#print f1.eval() 
    print(sess.run(f2)) 

[3 5 3]
[1 3 3]


In [4]:
#3.了解`TensorArray`的基本用法，并尝试配合`tf.while_loop`配合使用

#TensorArray可以看做是具有动态size功能的Tensor数组
#例如：将[2.4, 3.5]写进TensorArray三次
import tensorflow as tf 
def cond(time, output_ta_l): 
    return tf.less(time, 3) 
def body(time, output_ta_l): 
    output_ta_l = output_ta_l.write(time, [2.4, 3.5]) 
    return time + 1, output_ta_l 
time = tf.constant(0) 
output_ta = tf.TensorArray(dtype=tf.float32, size=1, dynamic_size=True) 
result = tf.while_loop(cond, body, loop_vars=[time, output_ta]) 
last_time, last_out = result 
final_out = last_out.stack() 
with tf.Session(): 
    print(last_time.eval()) 
    print(final_out.eval())

3
[[2.4 3.5]
 [2.4 3.5]
 [2.4 3.5]]
